//
// File generated by /ds50/app/products/root/v5_34_25/Linux64bit+2.6-2.12-e6-prof/bin/rootcint at Mon Aug  3 13:09:51 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SladDSTMain_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SladDSTMain_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void SladDSTClass_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_SladDSTClass(void *p = 0);
   static void *newArray_SladDSTClass(Long_t size, void *p);
   static void delete_SladDSTClass(void *p);
   static void deleteArray_SladDSTClass(void *p);
   static void destruct_SladDSTClass(void *p);
   static void streamer_SladDSTClass(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SladDSTClass*)
   {
      ::SladDSTClass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SladDSTClass >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SladDSTClass", ::SladDSTClass::Class_Version(), "./SladDSTClass.h", 217,
                  typeid(::SladDSTClass), ::ROOT::DefineBehavior(ptr, ptr),
                  &::SladDSTClass::Dictionary, isa_proxy, 0,
                  sizeof(::SladDSTClass) );
      instance.SetNew(&new_SladDSTClass);
      instance.SetNewArray(&newArray_SladDSTClass);
      instance.SetDelete(&delete_SladDSTClass);
      instance.SetDeleteArray(&deleteArray_SladDSTClass);
      instance.SetDestructor(&destruct_SladDSTClass);
      instance.SetStreamerFunc(&streamer_SladDSTClass);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SladDSTClass*)
   {
      return GenerateInitInstanceLocal((::SladDSTClass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SladDSTClass*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr SladDSTClass::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *SladDSTClass::Class_Name()
{
   return "SladDSTClass";
}

//______________________________________________________________________________
const char *SladDSTClass::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SladDSTClass*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SladDSTClass::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SladDSTClass*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SladDSTClass::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SladDSTClass*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SladDSTClass::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SladDSTClass*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void SladDSTClass::Streamer(TBuffer &R__b)
{
   // Stream an object of class SladDSTClass.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void SladDSTClass::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SladDSTClass.
      TClass *R__cl = ::SladDSTClass::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "e", (void*)&e);
      R__insp.InspectMember("TPCEvent", (void*)&e, "e.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d", (void*)&d);
      R__insp.InspectMember("ODEvent", (void*)&d, "d.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t", (void*)&t);
      R__insp.InspectMember("DSTEvent", (void*)&t, "t.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_s1_late_min", &tpc_s1_late_min);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_s1_late_max", &tpc_s1_late_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_s1_min", &tpc_s1_min);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_s1_max", &tpc_s1_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_total_f90Nmin", &tpc_total_f90Nmin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_total_f90Nmax", &tpc_total_f90Nmax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_total_f90Gmin", &tpc_total_f90Gmin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_total_f90Gmax", &tpc_total_f90Gmax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_coinc_wind", &od_coinc_wind);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpc_path", &tpc_path);
      R__insp.InspectMember(tpc_path, "tpc_path.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_path", &od_path);
      R__insp.InspectMember(od_path, "od_path.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "out_path", &out_path);
      R__insp.InspectMember(out_path, "out_path.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "out_file", &out_file);
      R__insp.InspectMember(out_file, "out_file.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*DSTtree", &DSTtree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f", &f);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tpc_chain", &tpc_chain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*s2_fraction", &s2_fraction);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*masaxy", &masaxy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*jasonxy", &jasonxy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*od_chain", &od_chain);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_SladDSTClass(void *p) {
      return  p ? new(p) ::SladDSTClass : new ::SladDSTClass;
   }
   static void *newArray_SladDSTClass(Long_t nElements, void *p) {
      return p ? new(p) ::SladDSTClass[nElements] : new ::SladDSTClass[nElements];
   }
   // Wrapper around operator delete
   static void delete_SladDSTClass(void *p) {
      delete ((::SladDSTClass*)p);
   }
   static void deleteArray_SladDSTClass(void *p) {
      delete [] ((::SladDSTClass*)p);
   }
   static void destruct_SladDSTClass(void *p) {
      typedef ::SladDSTClass current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_SladDSTClass(TBuffer &buf, void *obj) {
      ((::SladDSTClass*)obj)->::SladDSTClass::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::SladDSTClass

/********************************************************
* SladDSTMain_dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSladDSTMain_dict();

extern "C" void G__set_cpp_environmentSladDSTMain_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("SladDSTClass.h");
  G__cpp_reset_tagtableSladDSTMain_dict();
}
#include <new>
extern "C" int G__cpp_dllrevSladDSTMain_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SladDSTClass */
static int G__SladDSTMain_dict_648_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SladDSTClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SladDSTClass[n];
     } else {
       p = new((void*) gvp) SladDSTClass[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SladDSTClass;
     } else {
       p = new((void*) gvp) SladDSTClass;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->Init();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->add_tpctree((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->add_odtree((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->load_tpctree((TChain*) G__int(libp->para[0]), *(TPCEvent*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->load_odtree((TChain*) G__int(libp->para[0]), *(ODEvent*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->create_tpcchain();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->create_odchain();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->add_tpcfriend();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->multiplicity_cut((Float_t) G__double(libp->para[0]), (Float_t) G__double(libp->para[1])
, (Float_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->SetOutTPCTree();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->SetOutODTree();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->PreLoop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->LoopOverChain());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->VerifyDataFile(*((TString*) G__int(libp->para[0]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->ReadRunList(*(vector<int>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->SetTPCPath(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((SladDSTClass*) G__getstructoffset())->GetTPCPath();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->SetODPath(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((SladDSTClass*) G__getstructoffset())->GetODPath();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->SetOutPath(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((SladDSTClass*) G__getstructoffset())->GetOutPath();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->SetOutFile(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((SladDSTClass*) G__getstructoffset())->GetOutFile();
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->CX1(*(TPCEvent*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->CX2(*(TPCEvent*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->CX3(*(TPCEvent*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->CX4(*(TPCEvent*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->CX8(*(TPCEvent*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->CX9(*(TPCEvent*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->Cut_Gamma((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SladDSTClass*) G__getstructoffset())->Cut_Neutron((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SladDSTClass::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SladDSTClass::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SladDSTClass::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SladDSTClass::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SladDSTClass*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SladDSTClass::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SladDSTClass::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SladDSTClass::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SladDSTMain_dict_648_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SladDSTClass::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SladDSTMain_dict_648_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SladDSTClass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SladDSTClass(*(SladDSTClass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SladDSTClass G__TSladDSTClass;
static int G__SladDSTMain_dict_648_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SladDSTClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SladDSTClass*) (soff+(sizeof(SladDSTClass)*i)))->~G__TSladDSTClass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SladDSTClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SladDSTClass*) (soff))->~G__TSladDSTClass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__SladDSTMain_dict_648_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SladDSTClass* dest = (SladDSTClass*) G__getstructoffset();
   *dest = *(SladDSTClass*) libp->para[0].ref;
   const SladDSTClass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SladDSTClass */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSladDSTMain_dict {
 public:
  G__Sizep2memfuncSladDSTMain_dict(): p(&G__Sizep2memfuncSladDSTMain_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSladDSTMain_dict::*p)();
};

size_t G__get_sizep2memfuncSladDSTMain_dict()
{
  G__Sizep2memfuncSladDSTMain_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSladDSTMain_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass))) {
     SladDSTClass *G__Lderived;
     G__Lderived=(SladDSTClass*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass),G__get_linked_tagnum(&G__SladDSTMain_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSladDSTMain_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__SladDSTMain_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SladDSTClass */
static void G__setup_memvarSladDSTClass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass));
   { SladDSTClass *p; p=(SladDSTClass*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->e)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TPCEvent),-1,-1,1,"e=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->d)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_ODEvent),-1,-1,1,"d=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_DSTEvent),-1,-1,1,"t=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"tpc_s1_late_min=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"tpc_s1_late_max=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"tpc_s1_min=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"tpc_s1_max=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"tpc_total_f90Nmin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"tpc_total_f90Nmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"tpc_total_f90Gmin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"tpc_total_f90Gmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"od_coinc_wind=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TString),-1,-1,4,"tpc_path=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TString),-1,-1,4,"od_path=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TString),-1,-1,4,"out_path=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TString),-1,-1,4,"out_file=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TTree),-1,-1,4,"DSTtree=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TFile),-1,-1,4,"f=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TChain),-1,-1,4,"tpc_chain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TChain),-1,-1,4,"s2_fraction=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TChain),-1,-1,4,"masaxy=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TChain),-1,-1,4,"jasonxy=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TChain),-1,-1,4,"od_chain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SladDSTMain_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSladDSTMain_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSladDSTClass(void) {
   /* SladDSTClass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass));
   G__memfunc_setup("SladDSTClass",1125,G__SladDSTMain_dict_648_0_1, 105, G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,G__SladDSTMain_dict_648_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("add_tpctree",1151,G__SladDSTMain_dict_648_0_3, 103, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("add_odtree",1035,G__SladDSTMain_dict_648_0_4, 103, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("load_tpctree",1270,G__SladDSTMain_dict_648_0_5, 103, -1, -1, 0, 2, 1, 1, 0, 
"U 'TChain' - 0 - - u 'TPCEvent' - 1 - e", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("load_odtree",1154,G__SladDSTMain_dict_648_0_6, 103, -1, -1, 0, 2, 1, 1, 0, 
"U 'TChain' - 0 - - u 'ODEvent' - 1 - d", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("create_tpcchain",1565,G__SladDSTMain_dict_648_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("create_odchain",1449,G__SladDSTMain_dict_648_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_tpcfriend",1351,G__SladDSTMain_dict_648_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("multiplicity_cut",1748,G__SladDSTMain_dict_648_0_10, 103, -1, -1, 0, 3, 1, 1, 0, 
"f - 'Float_t' 0 - - f - 'Float_t' 0 - - "
"f - 'Float_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOutTPCTree",1243,G__SladDSTMain_dict_648_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOutODTree",1159,G__SladDSTMain_dict_648_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PreLoop",705,G__SladDSTMain_dict_648_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoopOverChain",1305,G__SladDSTMain_dict_648_0_14, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("VerifyDataFile",1391,G__SladDSTMain_dict_648_0_15, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadRunList",1101,G__SladDSTMain_dict_648_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<int,allocator<int> >' 'vector<int>' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTPCPath",928,G__SladDSTMain_dict_648_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - var", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTPCPath",916,G__SladDSTMain_dict_648_0_18, 117, G__get_linked_tagnum(&G__SladDSTMain_dictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetODPath",844,G__SladDSTMain_dict_648_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - var", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetODPath",832,G__SladDSTMain_dict_648_0_20, 117, G__get_linked_tagnum(&G__SladDSTMain_dictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOutPath",1009,G__SladDSTMain_dict_648_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - var", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetOutPath",997,G__SladDSTMain_dict_648_0_22, 117, G__get_linked_tagnum(&G__SladDSTMain_dictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOutFile",996,G__SladDSTMain_dict_648_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - var", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetOutFile",984,G__SladDSTMain_dict_648_0_24, 117, G__get_linked_tagnum(&G__SladDSTMain_dictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CX1",204,G__SladDSTMain_dict_648_0_25, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TPCEvent' - 41 - e", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CX2",205,G__SladDSTMain_dict_648_0_26, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TPCEvent' - 41 - e", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CX3",206,G__SladDSTMain_dict_648_0_27, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TPCEvent' - 41 - e", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CX4",207,G__SladDSTMain_dict_648_0_28, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TPCEvent' - 41 - e", "< 1.; }", (void*) NULL, 0);
   G__memfunc_setup("CX8",211,G__SladDSTMain_dict_648_0_29, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TPCEvent' - 41 - e", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CX9",212,G__SladDSTMain_dict_648_0_30, 103, -1, -1, 0, 1, 1, 1, 0, "u 'TPCEvent' - 41 - e", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut_Gamma",878,G__SladDSTMain_dict_648_0_31, 103, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - - d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut_Neutron",1142,G__SladDSTMain_dict_648_0_32, 103, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - - d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__SladDSTMain_dict_648_0_33, 85, G__get_linked_tagnum(&G__SladDSTMain_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SladDSTClass::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SladDSTMain_dict_648_0_34, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SladDSTClass::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SladDSTMain_dict_648_0_35, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SladDSTClass::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SladDSTMain_dict_648_0_36, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SladDSTClass::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SladDSTMain_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SladDSTMain_dict_648_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SladDSTMain_dict_648_0_41, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SladDSTClass::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SladDSTMain_dict_648_0_42, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SladDSTClass::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SladDSTMain_dict_648_0_43, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SladDSTClass::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SladDSTMain_dict_648_0_44, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SladDSTClass::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("SladDSTClass", 1125, G__SladDSTMain_dict_648_0_45, (int) ('i'), G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass), -1, 0, 1, 1, 1, 0, "u 'SladDSTClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SladDSTClass", 1251, G__SladDSTMain_dict_648_0_46, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__SladDSTMain_dict_648_0_47, (int) ('u'), G__get_linked_tagnum(&G__SladDSTMain_dictLN_SladDSTClass), -1, 1, 1, 1, 1, 0, "u 'SladDSTClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSladDSTMain_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSladDSTMain_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSladDSTMain_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SladDSTMain_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TChain = { "TChain" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_TPCEvent = { "TPCEvent" , 115 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_ODEvent = { "ODEvent" , 115 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_DSTEvent = { "DSTEvent" , 115 , -1 };
G__linked_taginfo G__SladDSTMain_dictLN_SladDSTClass = { "SladDSTClass" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSladDSTMain_dict() {
  G__SladDSTMain_dictLN_TClass.tagnum = -1 ;
  G__SladDSTMain_dictLN_TBuffer.tagnum = -1 ;
  G__SladDSTMain_dictLN_TMemberInspector.tagnum = -1 ;
  G__SladDSTMain_dictLN_TObject.tagnum = -1 ;
  G__SladDSTMain_dictLN_TString.tagnum = -1 ;
  G__SladDSTMain_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_TFile.tagnum = -1 ;
  G__SladDSTMain_dictLN_TTree.tagnum = -1 ;
  G__SladDSTMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_TChain.tagnum = -1 ;
  G__SladDSTMain_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__SladDSTMain_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__SladDSTMain_dictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_TPCEvent.tagnum = -1 ;
  G__SladDSTMain_dictLN_ODEvent.tagnum = -1 ;
  G__SladDSTMain_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SladDSTMain_dictLN_DSTEvent.tagnum = -1 ;
  G__SladDSTMain_dictLN_SladDSTClass.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSladDSTMain_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TString);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TFile);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TTree);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TChain);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_TPCEvent);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_ODEvent);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_DSTEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SladDSTMain_dictLN_SladDSTClass),sizeof(SladDSTClass),-1,29952,(char*)NULL,G__setup_memvarSladDSTClass,G__setup_memfuncSladDSTClass);
}
extern "C" void G__cpp_setupSladDSTMain_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSladDSTMain_dict()");
  G__set_cpp_environmentSladDSTMain_dict();
  G__cpp_setup_tagtableSladDSTMain_dict();

  G__cpp_setup_inheritanceSladDSTMain_dict();

  G__cpp_setup_typetableSladDSTMain_dict();

  G__cpp_setup_memvarSladDSTMain_dict();

  G__cpp_setup_memfuncSladDSTMain_dict();
  G__cpp_setup_globalSladDSTMain_dict();
  G__cpp_setup_funcSladDSTMain_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSladDSTMain_dict();
  return;
}
class G__cpp_setup_initSladDSTMain_dict {
  public:
    G__cpp_setup_initSladDSTMain_dict() { G__add_setup_func("SladDSTMain_dict",(G__incsetup)(&G__cpp_setupSladDSTMain_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSladDSTMain_dict() { G__remove_setup_func("SladDSTMain_dict"); }
};
G__cpp_setup_initSladDSTMain_dict G__cpp_setup_initializerSladDSTMain_dict;

