/********************************************************************
* SladDSTMain_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SladDSTMain_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSladDSTMain_dict();
extern void G__cpp_setup_inheritanceSladDSTMain_dict();
extern void G__cpp_setup_typetableSladDSTMain_dict();
extern void G__cpp_setup_memvarSladDSTMain_dict();
extern void G__cpp_setup_globalSladDSTMain_dict();
extern void G__cpp_setup_memfuncSladDSTMain_dict();
extern void G__cpp_setup_funcSladDSTMain_dict();
extern void G__set_cpp_environmentSladDSTMain_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SladDSTClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SladDSTMain_dictLN_TClass;
extern G__linked_taginfo G__SladDSTMain_dictLN_TBuffer;
extern G__linked_taginfo G__SladDSTMain_dictLN_TMemberInspector;
extern G__linked_taginfo G__SladDSTMain_dictLN_TObject;
extern G__linked_taginfo G__SladDSTMain_dictLN_TString;
extern G__linked_taginfo G__SladDSTMain_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_TFile;
extern G__linked_taginfo G__SladDSTMain_dictLN_TTree;
extern G__linked_taginfo G__SladDSTMain_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_TChain;
extern G__linked_taginfo G__SladDSTMain_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SladDSTMain_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SladDSTMain_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_TPCEvent;
extern G__linked_taginfo G__SladDSTMain_dictLN_ODEvent;
extern G__linked_taginfo G__SladDSTMain_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SladDSTMain_dictLN_DSTEvent;
extern G__linked_taginfo G__SladDSTMain_dictLN_SladDSTClass;

/* STUB derived class for protected member access */
